docstrings_on_attributes: true
content_type_overrides:
  application/pdf: application/octet-stream
  image/jpeg: application/octet-stream
project_name_override: easybill-client
package_name_override: easybill_client